### ISSUE TITLE
Crash when proguardrules is set to true

### ISSUE THREAD

**Issue by kperreau** [notifee/react-native-notifee#21]
Hello.
I get this crash when i set proguardrules to true.
Any idea ?
Thank you.

**Crashlytics**
`Unable to get provider io.invertase.notifee.NotifeeInitProvider: org.greenrobot.eventbus.g: Subscriber class app.notifee.core.database.Database_Impl and its super classes have no public methods with the @Subscribe annotation`

**Comment by Ehesp** [comment]
Thanks for flagging, we know what the issue is there. Will sort ASAP.

**Comment by Salakar** [comment]
Hey I've pushed version 0.4.0 which should fix this, please could you try it out - thanks!

**Comment by kperreau** [comment]
Nop, still crashing. Should i add some progruad rules ?

`Fatal Exception: java.lang.ExceptionInInitializerError
       at app.notifee.core.Notifee.nz_n(Notifee.java:8)
       at app.notifee.core.Notifee.configure(Notifee.java:3)
       at io.invertase.notifee.NotifeeInitProvider.onCreate(NotifeeInitProvider.java:22)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
       at app.notifee.core.InitProvider.attachInfo(InitProvider.java:7)
       at android.app.ActivityThread.installProvider(ActivityThread.java:5157)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4752)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4692)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

`Caused by org.greenrobot.eventbus.e: Subscriber class app.notifee.core.r and its super classes have no public methods with the @Subscribe annotation
       at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods(SubscriberMethodFinder.java:67)
       at org.greenrobot.eventbus.EventBus.register(EventBus.java:140)
       at app.notifee.core.EventSubscriber.<init>(EventSubscriber.java:5)
       at app.notifee.core.EventSubscriber.<clinit>(EventSubscriber.java:1)
       at app.notifee.core.Notifee.nz_n(Notifee.java:8)
       at app.notifee.core.Notifee.configure(Notifee.java:3)
       at io.invertase.notifee.NotifeeInitProvider.onCreate(NotifeeInitProvider.java:22)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1748)
       at android.content.ContentProvider.attachInfo(ContentProvider.java:1723)
       at app.notifee.core.InitProvider.attachInfo(InitProvider.java:7)
       at android.app.ActivityThread.installProvider(ActivityThread.java:5157)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:4752)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4692)
       at android.app.ActivityThread.-wrap1(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by kperreau** [comment]
UP ?

**Comment by Salakar** [comment]
I've pushed something for this in 0.5.0 - please could you try it

**Comment by kperreau** [comment]
Still not work. No crash this time, but notification don't display.

**Comment by kperreau** [comment]
UP ?

**Comment by Salakar** [comment]
@kperreau could you make a separate issue with some more detail as this sounds like a different problem. Please provide more info on what type of build (e.g. release), if license has been correctly added (https://notifee.app/react-native/docs/license-keys) etc.

Thanks
